/**********************************/
// App Action
/**********************************/
export const FETCH_LOGTYPES_REQUEST = 'FETCH_LOGTYPES_REQUEST';
export const FETCH_LOGTYPES_SUCCESS = 'FETCH_LOGTYPES_SUCCESS';
export const FETCH_LOGTYPES_FAILURE = 'FETCH_LOGTYPES_FAILURE';

export const CHANGE_TITLE = 'CHANGE_TITLE';

/**********************************/
// Container Action
/**********************************/
export const FETCH_CONTAINERS_REQUEST = 'FETCH_CONTAINERS_REQUEST';
export const FETCH_CONTAINERS_SUCCESS = 'FETCH_CONTAINERS_SUCCESS';
export const FETCH_CONTAINERS_FAILURE = 'FETCH_CONTAINERS_FAILURE';

export const ADD_CONTAINER_REQUEST = 'ADD_CONTAINER_REQUEST';
export const ADD_CONTAINER_SUCCESS = 'ADD_CONTAINER_SUCCESS';
export const ADD_CONTAINER_FAILURE = 'ADD_CONTAINER_FAILURE';

export const DELETE_CONTAINER_REQUEST = 'DELETE_CONTAINER_REQUEST';
export const DELETE_CONTAINER_SUCCESS = 'DELETE_CONTAINER_SUCCESS';
export const DELETE_CONTAINER_FAILURE = 'DELETE_CONTAINER_FAILURE';

export const UPDATE_CONTAINER_REQUEST = 'UPDATE_CONTAINER_REQUEST';
export const UPDATE_CONTAINER_SUCCESS = 'UPDATE_CONTAINER_SUCCESS';
export const UPDATE_CONTAINER_FAILURE = 'UPDATE_CONTAINER_FAILURE';


/**********************************/
// Archive Action
/**********************************/
export const FETCH_ARCHIVES_REQUEST = 'FETCH_ARCHIVES_REQUEST';
export const FETCH_ARCHIVES_SUCCESS = 'FETCH_ARCHIVES_SUCCESS';
export const FETCH_ARCHIVES_FAILURE = 'FETCH_ARCHIVES_FAILURE';

export const ADD_ARCHIVE_REQUEST = 'ADD_ARCHIVE_REQUEST';
export const ADD_ARCHIVE_SUCCESS = 'ADD_ARCHIVE_SUCCESS';
export const ADD_ARCHIVE_FAILURE = 'ADD_ARCHIVE_FAILURE';

export const DELETE_ARCHIVE_REQUEST = 'DELETE_ARCHIVE_REQUEST';
export const DELETE_ARCHIVE_SUCCESS = 'DELETE_ARCHIVE_SUCCESS';
export const DELETE_ARCHIVE_FAILURE = 'DELETE_ARCHIVE_FAILURE';

/**********************************/
// LogFile Action
/**********************************/
export const FETCH_LOGFILES_REQUEST = 'FETCH_LOGFILES_REQUEST';
export const FETCH_LOGFILES_SUCCESS = 'FETCH_LOGFILES_SUCCESS';
export const FETCH_LOGFILES_FAILURE = 'FETCH_LOGFILES_FAILURE';

export const REGISTER_LOGFILE_REQUEST = 'REGISTER_LOGFILES_REQUEST';
export const REGISTER_LOGFILE_SUCCESS = 'REGISTER_LOGFILES_SUCCESS';
export const REGISTER_LOGFILE_FAILURE = 'REGISTER_LOGFILES_FAILURE';

export const UNREGISTER_LOGFILE_REQUEST = 'UNREGISTER_LOGFILES_REQUEST';
export const UNREGISTER_LOGFILE_SUCCESS = 'UNREGISTER_LOGFILES_SUCCESS';
export const UNREGISTER_LOGFILE_FAILURE = 'UNREGISTER_LOGFILES_FAILURE';

export const BULK_SET_LOGTYPE = 'BULK_SET_LOGTYPE ';
export const BULK_SET_EXTRA = 'BULK_SET_EXTRA ';
