/**********************************/
// Container Action
/**********************************/
export const FETCH_CONTAINERS_REQUEST = 'FETCH_CONTAINERS_REQUEST';
export const FETCH_CONTAINERS_SUCCESS = 'FETCH_CONTAINERS_SUCCESS';
export const FETCH_CONTAINERS_FAILURE = 'FETCH_CONTAINERS_FAILURE';

export const ADD_CONTAINER_REQUEST = 'ADD_CONTAINER_REQUEST';
export const ADD_CONTAINER_SUCCESS = 'ADD_CONTAINER_SUCCESS';
export const ADD_CONTAINER_FAILURE = 'ADD_CONTAINER_FAILURE';

export const DELETE_CONTAINER_REQUEST = 'DELETE_CONTAINER_REQUEST';
export const DELETE_CONTAINER_SUCCESS = 'DELETE_CONTAINER_SUCCESS';
export const DELETE_CONTAINER_FAILURE = 'DELETE_CONTAINER_FAILURE';

export const UPDATE_CONTAINER_REQUEST = 'UPDATE_CONTAINER_REQUEST';
export const UPDATE_CONTAINER_SUCCESS = 'UPDATE_CONTAINER_SUCCESS';
export const UPDATE_CONTAINER_FAILURE = 'UPDATE_CONTAINER_FAILURE';


/**********************************/
// Archive Action
/**********************************/
export const FETCH_ARCHIVES_REQUEST = 'FETCH_ARCHIVES_REQUEST';
export const FETCH_ARCHIVES_SUCCESS = 'FETCH_ARCHIVES_SUCCESS';
export const FETCH_ARCHIVES_FAILURE = 'FETCH_ARCHIVES_FAILURE';

export const ADD_ARCHIVE_REQUEST = 'ADD_ARCHIVE_REQUEST';
export const ADD_ARCHIVE_SUCCESS = 'ADD_ARCHIVE_SUCCESS';
export const ADD_ARCHIVE_FAILURE = 'ADD_ARCHIVE_FAILURE';

